package javaTut;

public class _16Student {
//	private String name;
//	private int age;
//	
//	public String getName() {
//		return name;
//	}
//	public void setName(String name) {
//		this.name = name;		//	generated by eclipse
//	}							//	rightclick => sources => getter and setter
//	public int getAge() {
//		return age;
//	}
//	public void setAge(int age) {
//		this.age = age;
//	}
	
//	public int getAge() {
//		return this.age;
//	}
//	public void setAge(int age) {
//		if(age > 20 || age < 5){
//			System.out.println("Your age is too high or too low to be a student"); 
//			}else this.age = age;
//	}
//	public String getName() {
//		return this.name;
//	}
//	public void setName(String name) {
//		this.name = name;
//	}
}
